language: php
php:
  - 5.6
  - hhvm
  - nightly

install: composer install --dev
script: ./vendor/bin/phpunit tests/DatabaseTest.php --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry php vendor/bin/coveralls